try{
    console.log("code running")
}
catch(err)
{
    console.log("error there")
    console.log(p);
}
finally{
    console.log("running")
}